[workspace]
members = ["apps/job-consumer", "crates/ic-jobs", "crates/jobs-canister-tests"]
default-members = ["crates/ic-jobs"]
resolver = "3"

[workspace.package]
version = "0.5.3"
edition = "2024"
rust-version = "1.88"
license = "MIT"
description = "Durable application job policies for Internet Computer canisters"
repository = "https://github.com/dragginzgame/ic-jobs"

[workspace.dependencies]
candid = "0.10"
ic-cdk = "0.20"
ic-jobs = { path = "crates/ic-jobs" }
ic-memory = "0.35"
ic-testkit = "0.33"
ic-timers = "0.17"
jobs-test-consumer = { path = "apps/job-consumer" }
serde = "1.0"
serde_json = "1.0"

[workspace.lints.rust]
missing_docs = "deny"
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "warn"
